# Generated by Django 3.2.11 on 2022-01-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220121_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='students',
            new_name='teachers',
        ),
    ]
